apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-node-k8s
  name: simple-node-k8s-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/simple-node-k8s
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-node-k8s
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
